# This is a generated TOML EDI Specification

transaction_set_id = "850"
transaction_map    = ''


[export_rules]

  trans_set_id           = "transaction_set_id"
  customer_ref_num       = "components.customer_ref_num"
  order_type             = "components.order_type"
  po_num                 = "components.po_num"
  po_date                = "components.po_date"
  ship_to                = "components.ship_to.id_code_qual"
  no_deliver_after       = "components.no_deliver_after"
  no_deliver_before      = "components.no_deliver_before"
  sale_req_code          = "components.sale_req_code"
  seg_count              = "components.seg_count"
  trans_set_ctrl_num     = "components.trans_set_ctrl_num"
  trans_set_purpose_code = "components.trans_set_purpose_code"
  line_item_count        = "components.transaction_totals.line_item_count"
  [export_rules.item_data]
    KEY                        = "item_data"
    assigned_id                = "components.assigned_id"
    order_quant                = "components.order_quant"
    unit_price                 = "components.unit_price"
    unit_price_basis_code      = "components.unit_price_basis_code"
    uom                        = "components.uom"
    upc_ean_consumer_pack_code = "components.upc_ean_consumer_pack_code"


[[components]]
  type     = "segment"
  id       = "st"
  required = true
  max_use  = 1

  [[components.elements]]
    id       = "trans_set_id"
    required = true

  [[components.elements]]
    id       = "trans_set_ctrl_num"
    required = true

[[components]]
  type     = "segment"
  id       = "beg"
  required = true
  max_use  = 1

  [[components.elements]]
    id       = "trans_set_purpose_code"
    required = true

  [[components.elements]]
    id       = "order_type"
    required = true

  [[components.elements]]
    id       = "po_num"
    required = true

  [[components.elements]]
  [[components.elements]]
    id       = "po_date"
    required = true

[[components]]
  type     = "segment"
  id       = "ref"
  required = true

  [[components.elements]]
    id       = "ref_id_qualifier"
    required = true
    options  = "CR"

  [[components.elements]]
    id        = "reference_id"
    qualifier = "ref_id_qualifier"
    quality   = { CR = "customer_ref_num" }

[[components]]
  type = "segment"
  id   = "ref"

  [[components.elements]]
    id       = "ref_id_qualifier"
    required = true
    options  = "PD"

  [[components.elements]]
    id        = "reference_id"
    qualifier = "ref_id_qualifier"
    quality   = { CR = "promo_ref_num" }

[[components]]
  type = "segment"
  id   = "fob"

  [[components.elements]]
    id       = "ship_pay_method"
    required = true
    options  = ["bp", "cc", "df", "fo", "pp", "ps"]

  [[components.elements]]
    id      = "trans_terms_qual_code"
    options = "01"

  [[components.elements]]
    id = "trans_terms_code"
    options = [
      "cfr",
      "cif",
      "cip",
      "cpt",
      "daf",
      "ddp",
      "ddu",
      "exw",
      "fca",
      "fob",
    ]

  [[components.elements]]
    id      = "loc_qual"
    options = "ov"

  [[components.elements]]
    id = "desc"

[[components]]
  type     = "segment"
  id       = "csh"
  required = true
  max_use  = 5

  [[components.elements]]
    id      = "sale_req_code"
    options = ["n", "y", "+"]

[[components]]
  type    = "segment"
  id      = "dtm"
  max_use = 10

  [[components.elements]]
    id       = "dtm_qual"
    required = true
    options  = "063"

  [[components.elements]]
    id        = "date"
    qualifier = "dtm_qual"

    [components.elements.quality]
      064 = "no_deliver_after"
      063 = "no_deliver_before"

  [[components]]
    type    = "segment"
    id      = "dtm"
    max_use = 10

    [[components.elements]]
      id       = "dtm_qual"
      required = true
      options  = "064"

    [[components.elements]]
      id        = "date"
      qualifier = "dtm_qual"

      [components.elements.quality]
        064 = "no_deliver_after"
        063 = "no_deliver_before"

    [[components]]
      type    = "segment"
      id      = "pkg"
      max_use = 10

      [[components.elements]]
        id      = "item_desk_type"
        options = "F"

      [[components.elements]]
        id      = "pack_characteristic_code"
        options = "CS"

      [[components.elements]]
        id = "desc"

    [[components]]
      type       = "loop"
      id         = "n9"
      required   = true
      repetition = 1000
      name       = "reference_id"

      [[components.loop]]
        type     = "segment"
        id       = "n9"
        required = true
        max_use  = 1

        [[components.loop.elements]]
          id       = "ref_id_qual"
          required = true
          options  = "L1"

        [[components.loop.elements]]
          id        = "ref_id"
          qualifier = "ref_id_qual"
          quality   = { L1 = "letters_or_notes" }

      [[components.loop]]
        type     = "segment"
        id       = "msg"
        required = true
        max_use  = 1000

        [[components.loop.elements]]
          id       = "message_text"
          required = true

      [[components]]
        type       = "loop"
        id         = "n1"
        required   = true
        export_key = "entity_id_code"
        export_as  = { ST = "ship_to" }
        repetition = 1
        name       = "name"

        [[components.loop]]
          type     = "segment"
          id       = "n1"
          required = true
          max_use  = 1

          [[components.loop.elements]]
            id       = "entity_id_code"
            required = true
            options  = "ST"

          [[components.loop.elements]]
          [[components.loop.elements]]
            id       = "id_code_qual"
            required = true
            options  = ["15", "92", "ZZ"]

            [components.loop.elements.mapping]
              15 = "standard_address_num"
              92 = "assigned_by_buyer"
              ZZ = "mutually_defined"

          [[components.loop.elements]]
            id       = "id_code"
            required = true

        [[components]]
          type       = "loop"
          id         = "po1"
          required   = true
          repetition = 100000
          name       = "item_data"

          [[components.loop]]
            type     = "segment"
            id       = "po1"
            required = true
            max_use  = 1

            [[components.loop.elements]]
              id       = "assigned_id"
              required = true

            [[components.loop.elements]]
              id       = "order_quant"
              required = true

            [[components.loop.elements]]
              id       = "uom"
              required = true
              options  = ["CA", "EA"]

            [[components.loop.elements]]
              id       = "unit_price"
              required = true

            [[components.loop.elements]]
              id       = "unit_price_basis_code"
              required = true
              options  = ["PE", "RE"]

            [[components.loop.elements]]
              id       = "prod_id_qual"
              required = true
              options  = ["BP", "EN", "IB", "UA", "UK", "UP", "VN"]

            [[components.loop.elements]]
              id        = "prod_id"
              required  = true
              qualifier = "prod_id_qual"

              [components.loop.elements.quality]
                BP = "buyers_part_num"
                EN = "ean"
                IB = "isbn"
                UA = "upc_ean_case_code"
                UK = "upc_ean_ship_container_code"
                UP = "upc_ean_consumer_pack_code"
                VN = "vendors_item_num"

            [[components]]
              type       = "loop"
              id         = "ctt"
              required   = true
              repetition = 1
              name       = "transaction_totals"

              [[components.loop]]
                type     = "segment"
                id       = "ctt"
                required = true
                max_use  = 1

                [[components.loop.elements]]
                  id       = "line_item_count"
                  required = true

                [[components.loop.elements]]
                  id       = "hash_total"
                  required = true

              [[components]]
                type     = "segment"
                id       = "se"
                required = true
                max_use  = 1

                [[components.elements]]
                  id       = "seg_count"
                  required = true

                [[components.elements]]
                  id       = "trans_set_ctrl_num"
                  required = true
                  multiple = true
