# This is a generated TOML EDI Specification

transaction_set_id = "850"

[[components]]
type = "segment"
id = "st"
required = true
max_use = 1

  [[components.elements]]
  id = "trans_set_id"
  required = true

  [[components.elements]]
  id = "trans_set_ctrl_num"
  required = true

[[components]]
type = "segment"
id = "beg"
required = true
max_use = 1

  [[components.elements]]
  id = "trans_set_purpose_code"
  required = true

  [[components.elements]]
  id = "order_type"
  required = true

  [[components.elements]]
  id = "po_num"
  required = true

  [[components.elements]]
  id = "date"
  required = true

[[components]]
type = "segment"
id = "ref"
required = true
max_use = 0

  [[components.elements]]
  id = "ref_id_qualifier"
  required = true
  options = "CR"

  [[components.elements]]
  id = "customer_ref_num"

[[components]]
type = "segment"
id = "ref"
required = false
max_use = 0

  [[components.elements]]
  id = "re_id_qualifier"
  required = true
  options = "PD"

  [[components.elements]]
  id = "promo_ref_num"

[[components]]
type = "segment"
id = "fob"
required = false
max_use = 0

  [[components.elements]]
  id = "ship_pay_method"
  required = true
  options = ["bp", "cc", "df", "fo", "pp", "ps"]

  [[components.elements]]
  id = "trans_terms_qual_code"
  options = "01"

  [[components.elements]]
  id = "trans_terms_code"
  options = ["cfr", "cif", "cip", "cpt", "daf", "ddp", "ddu", "exw", "fca", "fob"]

  [[components.elements]]
  id = "loc_qual"
  options = "ov"

  [[components.elements]]
  id = "desc"

[[components]]
type = "segment"
id = "csh"
required = true
max_use = 5

  [[components.elements]]
  id = "sale_req_code"
  options = ["n", "y", "+"]

[[components]]
type = "segment"
id = "dtm"
required = false
max_use = 10

  [[components.elements]]
  id = "dtm_qual"
  required = true
  options = "063"

  [[components.elements]]
  id = "date"

[[components]]
type = "segment"
id = "dtm"
required = false
max_use = 10

  [[components.elements]]
  id = "dtm_qual"
  required = true
  options = "064"

  [[components.elements]]
  id = "date"

[[components]]
type = "segment"
id = "pkg"
required = false
max_use = 10

  [[components.elements]]
  id = "item_desk_type"
  options = "F"

  [[components.elements]]
  id = "pack_characteristic_code"
  options = "CS"

  [[components.elements]]
  id = "desc"

[[components]]
type = "loop"
id = "n9"
required = true
repetition = 1000

  [[components.loop]]
  type = "segment"
  id = "n9"
  required = true
  max_use = 1

    [[components.loop.elements]]
    id = "ref_id_qual"
    required = true
    options = "L1"

    [[components.loop.elements]]
    id = "ref_id"

  [[components.loop]]
  type = "segment"
  id = "msg"
  required = true
  max_use = 1000

    [[components.loop.elements]]
    id = "message_text"
    required = true

[[components]]
type = "loop"
id = "n1"
required = true
repetition = 1

  [[components.loop]]
  type = "segment"
  id = "n1"
  required = true
  max_use = 1

    [[components.loop.elements]]
    id = "entity_id_code"
    required = true
    options = "ST"

    [[components.loop.elements]]
    id = "id_code_qual"
    required = true
    options = ["15", "92", "ZZ"]

    [[components.loop.elements]]
    id = "id_code"
    required = true

[[components]]
type = "loop"
id = "po1"
required = true
repetition = 100000

  [[components.loop]]
  type = "segment"
  id = "po1"
  required = true
  max_use = 1

    [[components.loop.elements]]
    id = "assigned_id"
    required = true

    [[components.loop.elements]]
    id = "order_quant"
    required = true

    [[components.loop.elements]]
    id = "uom"
    required = true
    options = ["CA", "EA"]

    [[components.loop.elements]]
    id = "unit_price"
    required = true

    [[components.loop.elements]]
    id = "unit_price_basis_code"
    required = true
    options = ["PE", "RE"]

    [[components.loop.elements]]
    id = "prod_id_qual"
    required = true
    options = ["BP", "EN", "IB", "UA", "UK", "UP", "VN"]

    [[components.loop.elements]]
    id = "prod_id"
    required = true

[[components]]
type = "loop"
id = "ctt"
required = true
repetition = 1

  [[components.loop]]
  type = "segment"
  id = "ctt"
  required = true
  max_use = 1

    [[components.loop.elements]]
    id = "line_item_count"
    required = true

    [[components.loop.elements]]
    id = "hash_total"
    required = true

[[components]]
type = "segment"
id = "se"
required = true
max_use = 1

  [[components.elements]]
  id = "seg_count"
  required = true

  [[components.elements]]
  id = "trans_set_ctrl_num"
  required = true
