title       = "BasePurchaseOrder"
description = "An abstract Base Model for all Predi Transaction Models\nIf"
type        = "object"
required    = ['fields']

[properties]
  [properties.transaction_type]
    title   = "Transaction Type"
    default = "PurchaseOrder"
    type    = "string"

  [properties.fields]
    "$ref" = "#/definitions/PurchaseOrderFields"

[definitions]
  [definitions.POItemData]
    title       = "POItemData"
    description = "A Loop for containing nested, often repeatable data (e.g., ItemLoops)"
    type        = "object"
    required    = ['KEY', 'assigned_id', 'order_quant', 'unit_price', 'uom']

    [definitions.POItemData.properties]
      [definitions.POItemData.properties.KEY]
        title = "Key"
        type  = "string"

      [definitions.POItemData.properties.assigned_id]
        title = "Assigned Id"
        type  = "integer"

      [definitions.POItemData.properties.order_quant]
        title = "Order Quant"
        type  = "integer"

      [definitions.POItemData.properties.unit_price]
        title = "Unit Price"
        type  = "number"

      [definitions.POItemData.properties.unit_price_basis_code]
        title = "Unit Price Basis Code"
        type  = "string"

      [definitions.POItemData.properties.uom]
        title = "Uom"
        type  = "string"

      [definitions.POItemData.properties.upc_ean_consumer_pack_code]
        title = "Upc Ean Consumer Pack Code"
        type  = "string"

[definitions.PurchaseOrderFields]
  title = "PurchaseOrderFields"
  description = "Contains all fields (i.e., non-metadata) for PrediTransactions"
  type = "object"
  required = [
    'trans_set_id',
    'customer_ref_num',
    'order_type',
    'po_num',
    'po_date',
    'ship_to',
    'no_deliver_after',
    'no_deliver_before',
    'sale_req_code',
    'seg_count',
    'trans_set_ctrl_num',
    'trans_set_purpose_code',
    'line_item_count',
    'item_data',
  ]

  [definitions.PurchaseOrderFields.properties]
    [definitions.PurchaseOrderFields.properties.trans_set_id]
      title = "Trans Set Id"
      type  = "string"

    [definitions.PurchaseOrderFields.properties.customer_ref_num]
      title = "Customer Ref Num"
      type  = "string"

    [definitions.PurchaseOrderFields.properties.order_type]
      title = "Order Type"
      type  = "string"

    [definitions.PurchaseOrderFields.properties.po_num]
      title = "Po Num"
      type  = "string"

    [definitions.PurchaseOrderFields.properties.po_date]
      title = "Po Date"
      type  = "string"

    [definitions.PurchaseOrderFields.properties.ship_to]
      title = "Ship To"
      type  = "string"

    [definitions.PurchaseOrderFields.properties.no_deliver_after]
      title = "No Deliver After"
      type  = "string"

    [definitions.PurchaseOrderFields.properties.no_deliver_before]
      title = "No Deliver Before"
      type  = "string"

    [definitions.PurchaseOrderFields.properties.sale_req_code]
      title = "Sale Req Code"
      type  = "string"

    [definitions.PurchaseOrderFields.properties.seg_count]
      title = "Seg Count"
      type  = "string"

    [definitions.PurchaseOrderFields.properties.trans_set_ctrl_num]
      title = "Trans Set Ctrl Num"
      type  = "string"

    [definitions.PurchaseOrderFields.properties.trans_set_purpose_code]
      title = "Trans Set Purpose Code"
      type  = "string"

    [definitions.PurchaseOrderFields.properties.line_item_count]
      title = "Line Item Count"
      type  = "string"

    [definitions.PurchaseOrderFields.properties.item_data]
      "$ref" = "#/definitions/POItemData"
